//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleamart.TestClient.FleamartServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FleamartServiceReference.IFleamartService")]
    public interface IFleamartService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleamartService/TestOperation", ReplyAction="http://tempuri.org/IFleamartService/TestOperationResponse")]
        string TestOperation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleamartService/TestOperation", ReplyAction="http://tempuri.org/IFleamartService/TestOperationResponse")]
        System.Threading.Tasks.Task<string> TestOperationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFleamartServiceChannel : Fleamart.TestClient.FleamartServiceReference.IFleamartService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FleamartServiceClient : System.ServiceModel.ClientBase<Fleamart.TestClient.FleamartServiceReference.IFleamartService>, Fleamart.TestClient.FleamartServiceReference.IFleamartService {
        
        public FleamartServiceClient() {
        }
        
        public FleamartServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FleamartServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FleamartServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FleamartServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestOperation() {
            return base.Channel.TestOperation();
        }
        
        public System.Threading.Tasks.Task<string> TestOperationAsync() {
            return base.Channel.TestOperationAsync();
        }
    }
}
