
package com.fleamart.pm.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPrivatnoSporociloService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPrivatnoSporociloService {


    /**
     * 
     * @param ps
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DodajNovoSporocilo", action = "http://tempuri.org/IPrivatnoSporociloService/DodajNovoSporocilo")
    @WebResult(name = "DodajNovoSporociloResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DodajNovoSporocilo", targetNamespace = "http://tempuri.org/", className = "com.fleamart.pm.ws.DodajNovoSporocilo")
    @ResponseWrapper(localName = "DodajNovoSporociloResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.pm.ws.DodajNovoSporociloResponse")
    public Boolean dodajNovoSporocilo(
        @WebParam(name = "ps", targetNamespace = "http://tempuri.org/")
        PrivatnoSporocilo ps);

    /**
     * 
     * @param sporociloId
     * @param userId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IzbrisiSporocilo", action = "http://tempuri.org/IPrivatnoSporociloService/IzbrisiSporocilo")
    @WebResult(name = "IzbrisiSporociloResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IzbrisiSporocilo", targetNamespace = "http://tempuri.org/", className = "com.fleamart.pm.ws.IzbrisiSporocilo")
    @ResponseWrapper(localName = "IzbrisiSporociloResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.pm.ws.IzbrisiSporociloResponse")
    public Boolean izbrisiSporocilo(
        @WebParam(name = "UserId", targetNamespace = "http://tempuri.org/")
        Integer userId,
        @WebParam(name = "SporociloId", targetNamespace = "http://tempuri.org/")
        Integer sporociloId);

    /**
     * 
     * @param uporabnikId
     * @return
     *     returns com.fleamart.pm.ws.ArrayOfPrivatnoSporocilo
     */
    @WebMethod(operationName = "VrniPrivatnaSporocilaUporabnika", action = "http://tempuri.org/IPrivatnoSporociloService/VrniPrivatnaSporocilaUporabnika")
    @WebResult(name = "VrniPrivatnaSporocilaUporabnikaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VrniPrivatnaSporocilaUporabnika", targetNamespace = "http://tempuri.org/", className = "com.fleamart.pm.ws.VrniPrivatnaSporocilaUporabnika")
    @ResponseWrapper(localName = "VrniPrivatnaSporocilaUporabnikaResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.pm.ws.VrniPrivatnaSporocilaUporabnikaResponse")
    public ArrayOfPrivatnoSporocilo vrniPrivatnaSporocilaUporabnika(
        @WebParam(name = "UporabnikId", targetNamespace = "http://tempuri.org/")
        Integer uporabnikId);

    /**
     * 
     * @param sporociloId
     */
    @WebMethod(operationName = "OznaciSporociloKotPrebrano", action = "http://tempuri.org/IPrivatnoSporociloService/OznaciSporociloKotPrebrano")
    @RequestWrapper(localName = "OznaciSporociloKotPrebrano", targetNamespace = "http://tempuri.org/", className = "com.fleamart.pm.ws.OznaciSporociloKotPrebrano")
    @ResponseWrapper(localName = "OznaciSporociloKotPrebranoResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.pm.ws.OznaciSporociloKotPrebranoResponse")
    public void oznaciSporociloKotPrebrano(
        @WebParam(name = "SporociloId", targetNamespace = "http://tempuri.org/")
        Integer sporociloId);

}
