//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fleamart.TestClient.SupportTicketService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupportTicket", Namespace="http//www.fleamart.com/")]
    [System.SerializableAttribute()]
    public partial class SupportTicket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.Uporabnik AvtorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CasUstvarjenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CasZaprtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.SupportTicketKomentar[] KomentarjiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaslovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.SupportTicketKategorija SupportTicketKategorijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.SupportTicketStatus SupportTicketStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.Uporabnik TehnikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VsebinaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.Uporabnik Avtor {
            get {
                return this.AvtorField;
            }
            set {
                if ((object.ReferenceEquals(this.AvtorField, value) != true)) {
                    this.AvtorField = value;
                    this.RaisePropertyChanged("Avtor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CasUstvarjen {
            get {
                return this.CasUstvarjenField;
            }
            set {
                if ((this.CasUstvarjenField.Equals(value) != true)) {
                    this.CasUstvarjenField = value;
                    this.RaisePropertyChanged("CasUstvarjen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CasZaprt {
            get {
                return this.CasZaprtField;
            }
            set {
                if ((this.CasZaprtField.Equals(value) != true)) {
                    this.CasZaprtField = value;
                    this.RaisePropertyChanged("CasZaprt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.SupportTicketKomentar[] Komentarji {
            get {
                return this.KomentarjiField;
            }
            set {
                if ((object.ReferenceEquals(this.KomentarjiField, value) != true)) {
                    this.KomentarjiField = value;
                    this.RaisePropertyChanged("Komentarji");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naslov {
            get {
                return this.NaslovField;
            }
            set {
                if ((object.ReferenceEquals(this.NaslovField, value) != true)) {
                    this.NaslovField = value;
                    this.RaisePropertyChanged("Naslov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.SupportTicketKategorija SupportTicketKategorija {
            get {
                return this.SupportTicketKategorijaField;
            }
            set {
                if ((object.ReferenceEquals(this.SupportTicketKategorijaField, value) != true)) {
                    this.SupportTicketKategorijaField = value;
                    this.RaisePropertyChanged("SupportTicketKategorija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.SupportTicketStatus SupportTicketStatus {
            get {
                return this.SupportTicketStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.SupportTicketStatusField, value) != true)) {
                    this.SupportTicketStatusField = value;
                    this.RaisePropertyChanged("SupportTicketStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.Uporabnik Tehnik {
            get {
                return this.TehnikField;
            }
            set {
                if ((object.ReferenceEquals(this.TehnikField, value) != true)) {
                    this.TehnikField = value;
                    this.RaisePropertyChanged("Tehnik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vsebina {
            get {
                return this.VsebinaField;
            }
            set {
                if ((object.ReferenceEquals(this.VsebinaField, value) != true)) {
                    this.VsebinaField = value;
                    this.RaisePropertyChanged("Vsebina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Uporabnik", Namespace="http//www.fleamart.com/")]
    [System.SerializableAttribute()]
    public partial class Uporabnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GesloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.Naslov NaslovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriimekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.PrivatnoSporocilo[] PrivatnaSporocilaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.SeznamZelja[] SeznamZeljaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VlogaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Geslo {
            get {
                return this.GesloField;
            }
            set {
                if ((object.ReferenceEquals(this.GesloField, value) != true)) {
                    this.GesloField = value;
                    this.RaisePropertyChanged("Geslo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.Naslov Naslov {
            get {
                return this.NaslovField;
            }
            set {
                if ((object.ReferenceEquals(this.NaslovField, value) != true)) {
                    this.NaslovField = value;
                    this.RaisePropertyChanged("Naslov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priimek {
            get {
                return this.PriimekField;
            }
            set {
                if ((object.ReferenceEquals(this.PriimekField, value) != true)) {
                    this.PriimekField = value;
                    this.RaisePropertyChanged("Priimek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.PrivatnoSporocilo[] PrivatnaSporocila {
            get {
                return this.PrivatnaSporocilaField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivatnaSporocilaField, value) != true)) {
                    this.PrivatnaSporocilaField = value;
                    this.RaisePropertyChanged("PrivatnaSporocila");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.SeznamZelja[] SeznamZelja {
            get {
                return this.SeznamZeljaField;
            }
            set {
                if ((object.ReferenceEquals(this.SeznamZeljaField, value) != true)) {
                    this.SeznamZeljaField = value;
                    this.RaisePropertyChanged("SeznamZelja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Upime {
            get {
                return this.UpimeField;
            }
            set {
                if ((object.ReferenceEquals(this.UpimeField, value) != true)) {
                    this.UpimeField = value;
                    this.RaisePropertyChanged("Upime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vloga {
            get {
                return this.VlogaField;
            }
            set {
                if ((this.VlogaField.Equals(value) != true)) {
                    this.VlogaField = value;
                    this.RaisePropertyChanged("Vloga");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupportTicketKategorija", Namespace="http//www.fleamart.com/")]
    [System.SerializableAttribute()]
    public partial class SupportTicketKategorija : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupportTicketStatus", Namespace="http//www.fleamart.com/")]
    [System.SerializableAttribute()]
    public partial class SupportTicketStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis {
            get {
                return this.OpisField;
            }
            set {
                if ((object.ReferenceEquals(this.OpisField, value) != true)) {
                    this.OpisField = value;
                    this.RaisePropertyChanged("Opis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupportTicketKomentar", Namespace="http//www.fleamart.com/")]
    [System.SerializableAttribute()]
    public partial class SupportTicketKomentar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.Uporabnik AvtorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupportTicketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VsebinaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.Uporabnik Avtor {
            get {
                return this.AvtorField;
            }
            set {
                if ((object.ReferenceEquals(this.AvtorField, value) != true)) {
                    this.AvtorField = value;
                    this.RaisePropertyChanged("Avtor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Cas {
            get {
                return this.CasField;
            }
            set {
                if ((this.CasField.Equals(value) != true)) {
                    this.CasField = value;
                    this.RaisePropertyChanged("Cas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupportTicketId {
            get {
                return this.SupportTicketIdField;
            }
            set {
                if ((this.SupportTicketIdField.Equals(value) != true)) {
                    this.SupportTicketIdField = value;
                    this.RaisePropertyChanged("SupportTicketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vsebina {
            get {
                return this.VsebinaField;
            }
            set {
                if ((object.ReferenceEquals(this.VsebinaField, value) != true)) {
                    this.VsebinaField = value;
                    this.RaisePropertyChanged("Vsebina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Naslov", Namespace="http//www.fleamart.com/")]
    [System.SerializableAttribute()]
    public partial class Naslov : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrzavaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObcinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostnaStevilkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UlicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Drzava {
            get {
                return this.DrzavaField;
            }
            set {
                if ((object.ReferenceEquals(this.DrzavaField, value) != true)) {
                    this.DrzavaField = value;
                    this.RaisePropertyChanged("Drzava");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Obcina {
            get {
                return this.ObcinaField;
            }
            set {
                if ((object.ReferenceEquals(this.ObcinaField, value) != true)) {
                    this.ObcinaField = value;
                    this.RaisePropertyChanged("Obcina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostnaStevilka {
            get {
                return this.PostnaStevilkaField;
            }
            set {
                if ((this.PostnaStevilkaField.Equals(value) != true)) {
                    this.PostnaStevilkaField = value;
                    this.RaisePropertyChanged("PostnaStevilka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ulica {
            get {
                return this.UlicaField;
            }
            set {
                if ((object.ReferenceEquals(this.UlicaField, value) != true)) {
                    this.UlicaField = value;
                    this.RaisePropertyChanged("Ulica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrivatnoSporocilo", Namespace="http//www.fleamart.com/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class PrivatnoSporocilo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.Uporabnik PosiljateljField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PosiljateljIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrebranoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.Uporabnik PrejemnikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrejemnikIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrivatnoSporociloIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SporociloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Cas {
            get {
                return this.CasField;
            }
            set {
                if ((this.CasField.Equals(value) != true)) {
                    this.CasField = value;
                    this.RaisePropertyChanged("Cas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.Uporabnik Posiljatelj {
            get {
                return this.PosiljateljField;
            }
            set {
                if ((object.ReferenceEquals(this.PosiljateljField, value) != true)) {
                    this.PosiljateljField = value;
                    this.RaisePropertyChanged("Posiljatelj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PosiljateljId {
            get {
                return this.PosiljateljIdField;
            }
            set {
                if ((this.PosiljateljIdField.Equals(value) != true)) {
                    this.PosiljateljIdField = value;
                    this.RaisePropertyChanged("PosiljateljId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Prebrano {
            get {
                return this.PrebranoField;
            }
            set {
                if ((this.PrebranoField.Equals(value) != true)) {
                    this.PrebranoField = value;
                    this.RaisePropertyChanged("Prebrano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.Uporabnik Prejemnik {
            get {
                return this.PrejemnikField;
            }
            set {
                if ((object.ReferenceEquals(this.PrejemnikField, value) != true)) {
                    this.PrejemnikField = value;
                    this.RaisePropertyChanged("Prejemnik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrejemnikId {
            get {
                return this.PrejemnikIdField;
            }
            set {
                if ((this.PrejemnikIdField.Equals(value) != true)) {
                    this.PrejemnikIdField = value;
                    this.RaisePropertyChanged("PrejemnikId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrivatnoSporociloId {
            get {
                return this.PrivatnoSporociloIdField;
            }
            set {
                if ((this.PrivatnoSporociloIdField.Equals(value) != true)) {
                    this.PrivatnoSporociloIdField = value;
                    this.RaisePropertyChanged("PrivatnoSporociloId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sporocilo {
            get {
                return this.SporociloField;
            }
            set {
                if ((object.ReferenceEquals(this.SporociloField, value) != true)) {
                    this.SporociloField = value;
                    this.RaisePropertyChanged("Sporocilo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeznamZelja", Namespace="http//www.fleamart.com/")]
    [System.SerializableAttribute()]
    public partial class SeznamZelja : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.Oglas OglasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.Uporabnik UporabnikField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.Oglas Oglas {
            get {
                return this.OglasField;
            }
            set {
                if ((object.ReferenceEquals(this.OglasField, value) != true)) {
                    this.OglasField = value;
                    this.RaisePropertyChanged("Oglas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.Uporabnik Uporabnik {
            get {
                return this.UporabnikField;
            }
            set {
                if ((object.ReferenceEquals(this.UporabnikField, value) != true)) {
                    this.UporabnikField = value;
                    this.RaisePropertyChanged("Uporabnik");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Oglas", Namespace="http//www.fleamart.com/")]
    [System.SerializableAttribute()]
    public partial class Oglas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AvkcijaField;
        
        private Fleamart.TestClient.SupportTicketService.Uporabnik AvtorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CasDoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CasOdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CasSpremenjenoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.Kategorija KategorijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.Komentar[] KomentarjiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.Uporabnik KupecField;
        
        private string NaslovField;
        
        private string OpisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.Ponudba[] PonudbeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SlikeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusNakupaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> ZadnjaCenaAvkcijaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Avkcija {
            get {
                return this.AvkcijaField;
            }
            set {
                if ((this.AvkcijaField.Equals(value) != true)) {
                    this.AvkcijaField = value;
                    this.RaisePropertyChanged("Avkcija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Fleamart.TestClient.SupportTicketService.Uporabnik Avtor {
            get {
                return this.AvtorField;
            }
            set {
                if ((object.ReferenceEquals(this.AvtorField, value) != true)) {
                    this.AvtorField = value;
                    this.RaisePropertyChanged("Avtor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CasDo {
            get {
                return this.CasDoField;
            }
            set {
                if ((this.CasDoField.Equals(value) != true)) {
                    this.CasDoField = value;
                    this.RaisePropertyChanged("CasDo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CasOd {
            get {
                return this.CasOdField;
            }
            set {
                if ((this.CasOdField.Equals(value) != true)) {
                    this.CasOdField = value;
                    this.RaisePropertyChanged("CasOd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CasSpremenjeno {
            get {
                return this.CasSpremenjenoField;
            }
            set {
                if ((this.CasSpremenjenoField.Equals(value) != true)) {
                    this.CasSpremenjenoField = value;
                    this.RaisePropertyChanged("CasSpremenjeno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cena {
            get {
                return this.CenaField;
            }
            set {
                if ((this.CenaField.Equals(value) != true)) {
                    this.CenaField = value;
                    this.RaisePropertyChanged("Cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.Kategorija Kategorija {
            get {
                return this.KategorijaField;
            }
            set {
                if ((object.ReferenceEquals(this.KategorijaField, value) != true)) {
                    this.KategorijaField = value;
                    this.RaisePropertyChanged("Kategorija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.Komentar[] Komentarji {
            get {
                return this.KomentarjiField;
            }
            set {
                if ((object.ReferenceEquals(this.KomentarjiField, value) != true)) {
                    this.KomentarjiField = value;
                    this.RaisePropertyChanged("Komentarji");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.Uporabnik Kupec {
            get {
                return this.KupecField;
            }
            set {
                if ((object.ReferenceEquals(this.KupecField, value) != true)) {
                    this.KupecField = value;
                    this.RaisePropertyChanged("Kupec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Naslov {
            get {
                return this.NaslovField;
            }
            set {
                if ((object.ReferenceEquals(this.NaslovField, value) != true)) {
                    this.NaslovField = value;
                    this.RaisePropertyChanged("Naslov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Opis {
            get {
                return this.OpisField;
            }
            set {
                if ((object.ReferenceEquals(this.OpisField, value) != true)) {
                    this.OpisField = value;
                    this.RaisePropertyChanged("Opis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.Ponudba[] Ponudbe {
            get {
                return this.PonudbeField;
            }
            set {
                if ((object.ReferenceEquals(this.PonudbeField, value) != true)) {
                    this.PonudbeField = value;
                    this.RaisePropertyChanged("Ponudbe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Slike {
            get {
                return this.SlikeField;
            }
            set {
                if ((object.ReferenceEquals(this.SlikeField, value) != true)) {
                    this.SlikeField = value;
                    this.RaisePropertyChanged("Slike");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StatusNakupa {
            get {
                return this.StatusNakupaField;
            }
            set {
                if ((this.StatusNakupaField.Equals(value) != true)) {
                    this.StatusNakupaField = value;
                    this.RaisePropertyChanged("StatusNakupa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ZadnjaCenaAvkcija {
            get {
                return this.ZadnjaCenaAvkcijaField;
            }
            set {
                if ((this.ZadnjaCenaAvkcijaField.Equals(value) != true)) {
                    this.ZadnjaCenaAvkcijaField = value;
                    this.RaisePropertyChanged("ZadnjaCenaAvkcija");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kategorija", Namespace="http//www.fleamart.com/")]
    [System.SerializableAttribute()]
    public partial class Kategorija : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Komentar", Namespace="http//www.fleamart.com/")]
    [System.SerializableAttribute()]
    public partial class Komentar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Fleamart.TestClient.SupportTicketService.Uporabnik AvtorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        private string SporociloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Fleamart.TestClient.SupportTicketService.Uporabnik Avtor {
            get {
                return this.AvtorField;
            }
            set {
                if ((object.ReferenceEquals(this.AvtorField, value) != true)) {
                    this.AvtorField = value;
                    this.RaisePropertyChanged("Avtor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Cas {
            get {
                return this.CasField;
            }
            set {
                if ((this.CasField.Equals(value) != true)) {
                    this.CasField = value;
                    this.RaisePropertyChanged("Cas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Sporocilo {
            get {
                return this.SporociloField;
            }
            set {
                if ((object.ReferenceEquals(this.SporociloField, value) != true)) {
                    this.SporociloField = value;
                    this.RaisePropertyChanged("Sporocilo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ponudba", Namespace="http//www.fleamart.com/")]
    [System.SerializableAttribute()]
    public partial class Ponudba : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.Oglas OglasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fleamart.TestClient.SupportTicketService.Uporabnik UporabnikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ZnesekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Cas {
            get {
                return this.CasField;
            }
            set {
                if ((this.CasField.Equals(value) != true)) {
                    this.CasField = value;
                    this.RaisePropertyChanged("Cas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.Oglas Oglas {
            get {
                return this.OglasField;
            }
            set {
                if ((object.ReferenceEquals(this.OglasField, value) != true)) {
                    this.OglasField = value;
                    this.RaisePropertyChanged("Oglas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Fleamart.TestClient.SupportTicketService.Uporabnik Uporabnik {
            get {
                return this.UporabnikField;
            }
            set {
                if ((object.ReferenceEquals(this.UporabnikField, value) != true)) {
                    this.UporabnikField = value;
                    this.RaisePropertyChanged("Uporabnik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Znesek {
            get {
                return this.ZnesekField;
            }
            set {
                if ((this.ZnesekField.Equals(value) != true)) {
                    this.ZnesekField = value;
                    this.RaisePropertyChanged("Znesek");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SupportTicketService.ISupportTicketService")]
    public interface ISupportTicketService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/CreateSupportTicket", ReplyAction="http://tempuri.org/ISupportTicketService/CreateSupportTicketResponse")]
        bool CreateSupportTicket(Fleamart.TestClient.SupportTicketService.SupportTicket t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/CreateSupportTicket", ReplyAction="http://tempuri.org/ISupportTicketService/CreateSupportTicketResponse")]
        System.Threading.Tasks.Task<bool> CreateSupportTicketAsync(Fleamart.TestClient.SupportTicketService.SupportTicket t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/ReadSupportTicket", ReplyAction="http://tempuri.org/ISupportTicketService/ReadSupportTicketResponse")]
        Fleamart.TestClient.SupportTicketService.SupportTicket ReadSupportTicket(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/ReadSupportTicket", ReplyAction="http://tempuri.org/ISupportTicketService/ReadSupportTicketResponse")]
        System.Threading.Tasks.Task<Fleamart.TestClient.SupportTicketService.SupportTicket> ReadSupportTicketAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/UpdateSupportTicket", ReplyAction="http://tempuri.org/ISupportTicketService/UpdateSupportTicketResponse")]
        bool UpdateSupportTicket(Fleamart.TestClient.SupportTicketService.SupportTicket t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/UpdateSupportTicket", ReplyAction="http://tempuri.org/ISupportTicketService/UpdateSupportTicketResponse")]
        System.Threading.Tasks.Task<bool> UpdateSupportTicketAsync(Fleamart.TestClient.SupportTicketService.SupportTicket t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/DeleteSupportTicket", ReplyAction="http://tempuri.org/ISupportTicketService/DeleteSupportTicketResponse")]
        bool DeleteSupportTicket(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/DeleteSupportTicket", ReplyAction="http://tempuri.org/ISupportTicketService/DeleteSupportTicketResponse")]
        System.Threading.Tasks.Task<bool> DeleteSupportTicketAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/ListSupportTicket", ReplyAction="http://tempuri.org/ISupportTicketService/ListSupportTicketResponse")]
        Fleamart.TestClient.SupportTicketService.SupportTicket[] ListSupportTicket();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/ListSupportTicket", ReplyAction="http://tempuri.org/ISupportTicketService/ListSupportTicketResponse")]
        System.Threading.Tasks.Task<Fleamart.TestClient.SupportTicketService.SupportTicket[]> ListSupportTicketAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/CreateSupportTicketKategorija", ReplyAction="http://tempuri.org/ISupportTicketService/CreateSupportTicketKategorijaResponse")]
        bool CreateSupportTicketKategorija(Fleamart.TestClient.SupportTicketService.SupportTicketKategorija k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/CreateSupportTicketKategorija", ReplyAction="http://tempuri.org/ISupportTicketService/CreateSupportTicketKategorijaResponse")]
        System.Threading.Tasks.Task<bool> CreateSupportTicketKategorijaAsync(Fleamart.TestClient.SupportTicketService.SupportTicketKategorija k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/DeleteSupportTicketKategorija", ReplyAction="http://tempuri.org/ISupportTicketService/DeleteSupportTicketKategorijaResponse")]
        bool DeleteSupportTicketKategorija(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/DeleteSupportTicketKategorija", ReplyAction="http://tempuri.org/ISupportTicketService/DeleteSupportTicketKategorijaResponse")]
        System.Threading.Tasks.Task<bool> DeleteSupportTicketKategorijaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/ListSupportTicketKategorija", ReplyAction="http://tempuri.org/ISupportTicketService/ListSupportTicketKategorijaResponse")]
        Fleamart.TestClient.SupportTicketService.SupportTicketKategorija[] ListSupportTicketKategorija();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/ListSupportTicketKategorija", ReplyAction="http://tempuri.org/ISupportTicketService/ListSupportTicketKategorijaResponse")]
        System.Threading.Tasks.Task<Fleamart.TestClient.SupportTicketService.SupportTicketKategorija[]> ListSupportTicketKategorijaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/CreateSupportTicketStatus", ReplyAction="http://tempuri.org/ISupportTicketService/CreateSupportTicketStatusResponse")]
        bool CreateSupportTicketStatus(Fleamart.TestClient.SupportTicketService.SupportTicketStatus s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/CreateSupportTicketStatus", ReplyAction="http://tempuri.org/ISupportTicketService/CreateSupportTicketStatusResponse")]
        System.Threading.Tasks.Task<bool> CreateSupportTicketStatusAsync(Fleamart.TestClient.SupportTicketService.SupportTicketStatus s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/DeleteSupportTicketStatus", ReplyAction="http://tempuri.org/ISupportTicketService/DeleteSupportTicketStatusResponse")]
        bool DeleteSupportTicketStatus(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/DeleteSupportTicketStatus", ReplyAction="http://tempuri.org/ISupportTicketService/DeleteSupportTicketStatusResponse")]
        System.Threading.Tasks.Task<bool> DeleteSupportTicketStatusAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/ListSupportTicketStatus", ReplyAction="http://tempuri.org/ISupportTicketService/ListSupportTicketStatusResponse")]
        Fleamart.TestClient.SupportTicketService.SupportTicketStatus[] ListSupportTicketStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/ListSupportTicketStatus", ReplyAction="http://tempuri.org/ISupportTicketService/ListSupportTicketStatusResponse")]
        System.Threading.Tasks.Task<Fleamart.TestClient.SupportTicketService.SupportTicketStatus[]> ListSupportTicketStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/CreateSupportTicketKomentar", ReplyAction="http://tempuri.org/ISupportTicketService/CreateSupportTicketKomentarResponse")]
        bool CreateSupportTicketKomentar(Fleamart.TestClient.SupportTicketService.SupportTicketKomentar k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/CreateSupportTicketKomentar", ReplyAction="http://tempuri.org/ISupportTicketService/CreateSupportTicketKomentarResponse")]
        System.Threading.Tasks.Task<bool> CreateSupportTicketKomentarAsync(Fleamart.TestClient.SupportTicketService.SupportTicketKomentar k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/UpdateSupportTicketKomentar", ReplyAction="http://tempuri.org/ISupportTicketService/UpdateSupportTicketKomentarResponse")]
        bool UpdateSupportTicketKomentar(Fleamart.TestClient.SupportTicketService.SupportTicketKomentar k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/UpdateSupportTicketKomentar", ReplyAction="http://tempuri.org/ISupportTicketService/UpdateSupportTicketKomentarResponse")]
        System.Threading.Tasks.Task<bool> UpdateSupportTicketKomentarAsync(Fleamart.TestClient.SupportTicketService.SupportTicketKomentar k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/DeleteSupportTicketKomentar", ReplyAction="http://tempuri.org/ISupportTicketService/DeleteSupportTicketKomentarResponse")]
        bool DeleteSupportTicketKomentar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/DeleteSupportTicketKomentar", ReplyAction="http://tempuri.org/ISupportTicketService/DeleteSupportTicketKomentarResponse")]
        System.Threading.Tasks.Task<bool> DeleteSupportTicketKomentarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/ListSupportTicketKomentar", ReplyAction="http://tempuri.org/ISupportTicketService/ListSupportTicketKomentarResponse")]
        Fleamart.TestClient.SupportTicketService.SupportTicketKomentar[] ListSupportTicketKomentar(int supportTicketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/ListSupportTicketKomentar", ReplyAction="http://tempuri.org/ISupportTicketService/ListSupportTicketKomentarResponse")]
        System.Threading.Tasks.Task<Fleamart.TestClient.SupportTicketService.SupportTicketKomentar[]> ListSupportTicketKomentarAsync(int supportTicketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/ListUporabnik", ReplyAction="http://tempuri.org/ISupportTicketService/ListUporabnikResponse")]
        Fleamart.TestClient.SupportTicketService.Uporabnik[] ListUporabnik();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISupportTicketService/ListUporabnik", ReplyAction="http://tempuri.org/ISupportTicketService/ListUporabnikResponse")]
        System.Threading.Tasks.Task<Fleamart.TestClient.SupportTicketService.Uporabnik[]> ListUporabnikAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISupportTicketServiceChannel : Fleamart.TestClient.SupportTicketService.ISupportTicketService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupportTicketServiceClient : System.ServiceModel.ClientBase<Fleamart.TestClient.SupportTicketService.ISupportTicketService>, Fleamart.TestClient.SupportTicketService.ISupportTicketService {
        
        public SupportTicketServiceClient() {
        }
        
        public SupportTicketServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupportTicketServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupportTicketServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupportTicketServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateSupportTicket(Fleamart.TestClient.SupportTicketService.SupportTicket t) {
            return base.Channel.CreateSupportTicket(t);
        }
        
        public System.Threading.Tasks.Task<bool> CreateSupportTicketAsync(Fleamart.TestClient.SupportTicketService.SupportTicket t) {
            return base.Channel.CreateSupportTicketAsync(t);
        }
        
        public Fleamart.TestClient.SupportTicketService.SupportTicket ReadSupportTicket(int id) {
            return base.Channel.ReadSupportTicket(id);
        }
        
        public System.Threading.Tasks.Task<Fleamart.TestClient.SupportTicketService.SupportTicket> ReadSupportTicketAsync(int id) {
            return base.Channel.ReadSupportTicketAsync(id);
        }
        
        public bool UpdateSupportTicket(Fleamart.TestClient.SupportTicketService.SupportTicket t) {
            return base.Channel.UpdateSupportTicket(t);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSupportTicketAsync(Fleamart.TestClient.SupportTicketService.SupportTicket t) {
            return base.Channel.UpdateSupportTicketAsync(t);
        }
        
        public bool DeleteSupportTicket(int id) {
            return base.Channel.DeleteSupportTicket(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSupportTicketAsync(int id) {
            return base.Channel.DeleteSupportTicketAsync(id);
        }
        
        public Fleamart.TestClient.SupportTicketService.SupportTicket[] ListSupportTicket() {
            return base.Channel.ListSupportTicket();
        }
        
        public System.Threading.Tasks.Task<Fleamart.TestClient.SupportTicketService.SupportTicket[]> ListSupportTicketAsync() {
            return base.Channel.ListSupportTicketAsync();
        }
        
        public bool CreateSupportTicketKategorija(Fleamart.TestClient.SupportTicketService.SupportTicketKategorija k) {
            return base.Channel.CreateSupportTicketKategorija(k);
        }
        
        public System.Threading.Tasks.Task<bool> CreateSupportTicketKategorijaAsync(Fleamart.TestClient.SupportTicketService.SupportTicketKategorija k) {
            return base.Channel.CreateSupportTicketKategorijaAsync(k);
        }
        
        public bool DeleteSupportTicketKategorija(int id) {
            return base.Channel.DeleteSupportTicketKategorija(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSupportTicketKategorijaAsync(int id) {
            return base.Channel.DeleteSupportTicketKategorijaAsync(id);
        }
        
        public Fleamart.TestClient.SupportTicketService.SupportTicketKategorija[] ListSupportTicketKategorija() {
            return base.Channel.ListSupportTicketKategorija();
        }
        
        public System.Threading.Tasks.Task<Fleamart.TestClient.SupportTicketService.SupportTicketKategorija[]> ListSupportTicketKategorijaAsync() {
            return base.Channel.ListSupportTicketKategorijaAsync();
        }
        
        public bool CreateSupportTicketStatus(Fleamart.TestClient.SupportTicketService.SupportTicketStatus s) {
            return base.Channel.CreateSupportTicketStatus(s);
        }
        
        public System.Threading.Tasks.Task<bool> CreateSupportTicketStatusAsync(Fleamart.TestClient.SupportTicketService.SupportTicketStatus s) {
            return base.Channel.CreateSupportTicketStatusAsync(s);
        }
        
        public bool DeleteSupportTicketStatus(int id) {
            return base.Channel.DeleteSupportTicketStatus(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSupportTicketStatusAsync(int id) {
            return base.Channel.DeleteSupportTicketStatusAsync(id);
        }
        
        public Fleamart.TestClient.SupportTicketService.SupportTicketStatus[] ListSupportTicketStatus() {
            return base.Channel.ListSupportTicketStatus();
        }
        
        public System.Threading.Tasks.Task<Fleamart.TestClient.SupportTicketService.SupportTicketStatus[]> ListSupportTicketStatusAsync() {
            return base.Channel.ListSupportTicketStatusAsync();
        }
        
        public bool CreateSupportTicketKomentar(Fleamart.TestClient.SupportTicketService.SupportTicketKomentar k) {
            return base.Channel.CreateSupportTicketKomentar(k);
        }
        
        public System.Threading.Tasks.Task<bool> CreateSupportTicketKomentarAsync(Fleamart.TestClient.SupportTicketService.SupportTicketKomentar k) {
            return base.Channel.CreateSupportTicketKomentarAsync(k);
        }
        
        public bool UpdateSupportTicketKomentar(Fleamart.TestClient.SupportTicketService.SupportTicketKomentar k) {
            return base.Channel.UpdateSupportTicketKomentar(k);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSupportTicketKomentarAsync(Fleamart.TestClient.SupportTicketService.SupportTicketKomentar k) {
            return base.Channel.UpdateSupportTicketKomentarAsync(k);
        }
        
        public bool DeleteSupportTicketKomentar(int id) {
            return base.Channel.DeleteSupportTicketKomentar(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSupportTicketKomentarAsync(int id) {
            return base.Channel.DeleteSupportTicketKomentarAsync(id);
        }
        
        public Fleamart.TestClient.SupportTicketService.SupportTicketKomentar[] ListSupportTicketKomentar(int supportTicketId) {
            return base.Channel.ListSupportTicketKomentar(supportTicketId);
        }
        
        public System.Threading.Tasks.Task<Fleamart.TestClient.SupportTicketService.SupportTicketKomentar[]> ListSupportTicketKomentarAsync(int supportTicketId) {
            return base.Channel.ListSupportTicketKomentarAsync(supportTicketId);
        }
        
        public Fleamart.TestClient.SupportTicketService.Uporabnik[] ListUporabnik() {
            return base.Channel.ListUporabnik();
        }
        
        public System.Threading.Tasks.Task<Fleamart.TestClient.SupportTicketService.Uporabnik[]> ListUporabnikAsync() {
            return base.Channel.ListUporabnikAsync();
        }
    }
}
