
package com.fleamart.supportticket.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISupportTicketService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISupportTicketService {


    /**
     * 
     * @param t
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "CreateSupportTicket", action = "http://tempuri.org/ISupportTicketService/CreateSupportTicket")
    @WebResult(name = "CreateSupportTicketResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateSupportTicket", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.CreateSupportTicket")
    @ResponseWrapper(localName = "CreateSupportTicketResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.CreateSupportTicketResponse")
    public Boolean createSupportTicket(
        @WebParam(name = "t", targetNamespace = "http://tempuri.org/")
        SupportTicket t);

    /**
     * 
     * @param id
     * @return
     *     returns com.fleamart.supportticket.ws.SupportTicket
     */
    @WebMethod(operationName = "ReadSupportTicket", action = "http://tempuri.org/ISupportTicketService/ReadSupportTicket")
    @WebResult(name = "ReadSupportTicketResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReadSupportTicket", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.ReadSupportTicket")
    @ResponseWrapper(localName = "ReadSupportTicketResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.ReadSupportTicketResponse")
    public SupportTicket readSupportTicket(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Integer id);

    /**
     * 
     * @param t
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateSupportTicket", action = "http://tempuri.org/ISupportTicketService/UpdateSupportTicket")
    @WebResult(name = "UpdateSupportTicketResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateSupportTicket", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.UpdateSupportTicket")
    @ResponseWrapper(localName = "UpdateSupportTicketResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.UpdateSupportTicketResponse")
    public Boolean updateSupportTicket(
        @WebParam(name = "t", targetNamespace = "http://tempuri.org/")
        SupportTicket t);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DeleteSupportTicket", action = "http://tempuri.org/ISupportTicketService/DeleteSupportTicket")
    @WebResult(name = "DeleteSupportTicketResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteSupportTicket", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.DeleteSupportTicket")
    @ResponseWrapper(localName = "DeleteSupportTicketResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.DeleteSupportTicketResponse")
    public Boolean deleteSupportTicket(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Integer id);

    /**
     * 
     * @return
     *     returns com.fleamart.supportticket.ws.ArrayOfSupportTicket
     */
    @WebMethod(operationName = "ListSupportTicket", action = "http://tempuri.org/ISupportTicketService/ListSupportTicket")
    @WebResult(name = "ListSupportTicketResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListSupportTicket", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.ListSupportTicket")
    @ResponseWrapper(localName = "ListSupportTicketResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.ListSupportTicketResponse")
    public ArrayOfSupportTicket listSupportTicket();

    /**
     * 
     * @param k
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "CreateSupportTicketKategorija", action = "http://tempuri.org/ISupportTicketService/CreateSupportTicketKategorija")
    @WebResult(name = "CreateSupportTicketKategorijaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateSupportTicketKategorija", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.CreateSupportTicketKategorija")
    @ResponseWrapper(localName = "CreateSupportTicketKategorijaResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.CreateSupportTicketKategorijaResponse")
    public Boolean createSupportTicketKategorija(
        @WebParam(name = "k", targetNamespace = "http://tempuri.org/")
        SupportTicketKategorija k);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DeleteSupportTicketKategorija", action = "http://tempuri.org/ISupportTicketService/DeleteSupportTicketKategorija")
    @WebResult(name = "DeleteSupportTicketKategorijaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteSupportTicketKategorija", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.DeleteSupportTicketKategorija")
    @ResponseWrapper(localName = "DeleteSupportTicketKategorijaResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.DeleteSupportTicketKategorijaResponse")
    public Boolean deleteSupportTicketKategorija(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Integer id);

    /**
     * 
     * @return
     *     returns com.fleamart.supportticket.ws.ArrayOfSupportTicketKategorija
     */
    @WebMethod(operationName = "ListSupportTicketKategorija", action = "http://tempuri.org/ISupportTicketService/ListSupportTicketKategorija")
    @WebResult(name = "ListSupportTicketKategorijaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListSupportTicketKategorija", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.ListSupportTicketKategorija")
    @ResponseWrapper(localName = "ListSupportTicketKategorijaResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.ListSupportTicketKategorijaResponse")
    public ArrayOfSupportTicketKategorija listSupportTicketKategorija();

    /**
     * 
     * @param s
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "CreateSupportTicketStatus", action = "http://tempuri.org/ISupportTicketService/CreateSupportTicketStatus")
    @WebResult(name = "CreateSupportTicketStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateSupportTicketStatus", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.CreateSupportTicketStatus")
    @ResponseWrapper(localName = "CreateSupportTicketStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.CreateSupportTicketStatusResponse")
    public Boolean createSupportTicketStatus(
        @WebParam(name = "s", targetNamespace = "http://tempuri.org/")
        SupportTicketStatus s);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DeleteSupportTicketStatus", action = "http://tempuri.org/ISupportTicketService/DeleteSupportTicketStatus")
    @WebResult(name = "DeleteSupportTicketStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteSupportTicketStatus", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.DeleteSupportTicketStatus")
    @ResponseWrapper(localName = "DeleteSupportTicketStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.DeleteSupportTicketStatusResponse")
    public Boolean deleteSupportTicketStatus(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Integer id);

    /**
     * 
     * @return
     *     returns com.fleamart.supportticket.ws.ArrayOfSupportTicketStatus
     */
    @WebMethod(operationName = "ListSupportTicketStatus", action = "http://tempuri.org/ISupportTicketService/ListSupportTicketStatus")
    @WebResult(name = "ListSupportTicketStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListSupportTicketStatus", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.ListSupportTicketStatus")
    @ResponseWrapper(localName = "ListSupportTicketStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.ListSupportTicketStatusResponse")
    public ArrayOfSupportTicketStatus listSupportTicketStatus();

    /**
     * 
     * @param k
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "CreateSupportTicketKomentar", action = "http://tempuri.org/ISupportTicketService/CreateSupportTicketKomentar")
    @WebResult(name = "CreateSupportTicketKomentarResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateSupportTicketKomentar", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.CreateSupportTicketKomentar")
    @ResponseWrapper(localName = "CreateSupportTicketKomentarResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.CreateSupportTicketKomentarResponse")
    public Boolean createSupportTicketKomentar(
        @WebParam(name = "k", targetNamespace = "http://tempuri.org/")
        SupportTicketKomentar k);

    /**
     * 
     * @param k
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateSupportTicketKomentar", action = "http://tempuri.org/ISupportTicketService/UpdateSupportTicketKomentar")
    @WebResult(name = "UpdateSupportTicketKomentarResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateSupportTicketKomentar", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.UpdateSupportTicketKomentar")
    @ResponseWrapper(localName = "UpdateSupportTicketKomentarResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.UpdateSupportTicketKomentarResponse")
    public Boolean updateSupportTicketKomentar(
        @WebParam(name = "k", targetNamespace = "http://tempuri.org/")
        SupportTicketKomentar k);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DeleteSupportTicketKomentar", action = "http://tempuri.org/ISupportTicketService/DeleteSupportTicketKomentar")
    @WebResult(name = "DeleteSupportTicketKomentarResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteSupportTicketKomentar", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.DeleteSupportTicketKomentar")
    @ResponseWrapper(localName = "DeleteSupportTicketKomentarResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.DeleteSupportTicketKomentarResponse")
    public Boolean deleteSupportTicketKomentar(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Integer id);

    /**
     * 
     * @param supportTicketId
     * @return
     *     returns com.fleamart.supportticket.ws.ArrayOfSupportTicketKomentar
     */
    @WebMethod(operationName = "ListSupportTicketKomentar", action = "http://tempuri.org/ISupportTicketService/ListSupportTicketKomentar")
    @WebResult(name = "ListSupportTicketKomentarResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListSupportTicketKomentar", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.ListSupportTicketKomentar")
    @ResponseWrapper(localName = "ListSupportTicketKomentarResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.supportticket.ws.ListSupportTicketKomentarResponse")
    public ArrayOfSupportTicketKomentar listSupportTicketKomentar(
        @WebParam(name = "supportTicketId", targetNamespace = "http://tempuri.org/")
        Integer supportTicketId);

}
