
package com.fleamart.supportticket.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SupportTicketService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:1691/SupportTicketService.svc?wsdl")
public class SupportTicketService
    extends Service
{

    private final static URL SUPPORTTICKETSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUPPORTTICKETSERVICE_EXCEPTION;
    private final static QName SUPPORTTICKETSERVICE_QNAME = new QName("http://tempuri.org/", "SupportTicketService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1691/SupportTicketService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUPPORTTICKETSERVICE_WSDL_LOCATION = url;
        SUPPORTTICKETSERVICE_EXCEPTION = e;
    }

    public SupportTicketService() {
        super(__getWsdlLocation(), SUPPORTTICKETSERVICE_QNAME);
    }

    public SupportTicketService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUPPORTTICKETSERVICE_QNAME, features);
    }

    public SupportTicketService(URL wsdlLocation) {
        super(wsdlLocation, SUPPORTTICKETSERVICE_QNAME);
    }

    public SupportTicketService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUPPORTTICKETSERVICE_QNAME, features);
    }

    public SupportTicketService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SupportTicketService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISupportTicketService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISupportTicketService")
    public ISupportTicketService getBasicHttpBindingISupportTicketService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISupportTicketService"), ISupportTicketService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISupportTicketService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISupportTicketService")
    public ISupportTicketService getBasicHttpBindingISupportTicketService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISupportTicketService"), ISupportTicketService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUPPORTTICKETSERVICE_EXCEPTION!= null) {
            throw SUPPORTTICKETSERVICE_EXCEPTION;
        }
        return SUPPORTTICKETSERVICE_WSDL_LOCATION;
    }

}
