
package com.fleamart.seznamZelja.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISeznamZeljaService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISeznamZeljaService {


    /**
     * 
     * @param u
     * @param s
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "http://tempuri.org/ISeznamZeljaService/dodajZeljo")
    @WebResult(name = "dodajZeljoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "dodajZeljo", targetNamespace = "http://tempuri.org/", className = "com.fleamart.seznamZelja.ws.DodajZeljo")
    @ResponseWrapper(localName = "dodajZeljoResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.seznamZelja.ws.DodajZeljoResponse")
    public Boolean dodajZeljo(
        @WebParam(name = "s", targetNamespace = "http://tempuri.org/")
        Oglas s,
        @WebParam(name = "u", targetNamespace = "http://tempuri.org/")
        Uporabnik u);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "http://tempuri.org/ISeznamZeljaService/izbrisiZeljo")
    @WebResult(name = "izbrisiZeljoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "izbrisiZeljo", targetNamespace = "http://tempuri.org/", className = "com.fleamart.seznamZelja.ws.IzbrisiZeljo")
    @ResponseWrapper(localName = "izbrisiZeljoResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.seznamZelja.ws.IzbrisiZeljoResponse")
    public Boolean izbrisiZeljo(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Integer id);

    /**
     * 
     * @param uporabnikId
     * @return
     *     returns com.fleamart.seznamZelja.ws.ArrayOfOglas
     */
    @WebMethod(action = "http://tempuri.org/ISeznamZeljaService/pridobiSeznamZelja")
    @WebResult(name = "pridobiSeznamZeljaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "pridobiSeznamZelja", targetNamespace = "http://tempuri.org/", className = "com.fleamart.seznamZelja.ws.PridobiSeznamZelja")
    @ResponseWrapper(localName = "pridobiSeznamZeljaResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.seznamZelja.ws.PridobiSeznamZeljaResponse")
    public ArrayOfOglas pridobiSeznamZelja(
        @WebParam(name = "uporabnikId", targetNamespace = "http://tempuri.org/")
        Integer uporabnikId);

}
