// <auto-generated />
namespace Fleamart.Dal.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class am4db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(am4db));
        
        string IMigrationMetadata.Id
        {
            get { return "201212191719244_am4db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
