// <auto-generated />
namespace Fleamart.Dal.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EditPonudba : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditPonudba));
        
        string IMigrationMetadata.Id
        {
            get { return "201212181446580_EditPonudba"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
