
package com.fleamart.kategorija.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IKategorijaService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IKategorijaService {


    /**
     * 
     * @return
     *     returns com.fleamart.kategorija.ws.ArrayOfKategorija
     */
    @WebMethod(operationName = "VrniKategorije", action = "http://tempuri.org/IKategorijaService/VrniKategorije")
    @WebResult(name = "VrniKategorijeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VrniKategorije", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.VrniKategorije")
    @ResponseWrapper(localName = "VrniKategorijeResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.VrniKategorijeResponse")
    public ArrayOfKategorija vrniKategorije();

    /**
     * 
     * @param k
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DodajKategorijo", action = "http://tempuri.org/IKategorijaService/DodajKategorijo")
    @WebResult(name = "DodajKategorijoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DodajKategorijo", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.DodajKategorijo")
    @ResponseWrapper(localName = "DodajKategorijoResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.DodajKategorijoResponse")
    public Boolean dodajKategorijo(
        @WebParam(name = "k", targetNamespace = "http://tempuri.org/")
        Kategorija k);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IzbrisiKategorijo", action = "http://tempuri.org/IKategorijaService/IzbrisiKategorijo")
    @WebResult(name = "IzbrisiKategorijoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IzbrisiKategorijo", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.IzbrisiKategorijo")
    @ResponseWrapper(localName = "IzbrisiKategorijoResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.IzbrisiKategorijoResponse")
    public Boolean izbrisiKategorijo(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Integer id);

}
