
package com.fleamart.kategorija.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IKategorijaService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IKategorijaService {


    /**
     * 
     * @return
     *     returns com.fleamart.kategorija.ws.ArrayOfKategorija
     */
    @WebMethod(operationName = "VrniKategorije", action = "http://tempuri.org/IKategorijaService/VrniKategorije")
    @WebResult(name = "VrniKategorijeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VrniKategorije", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.VrniKategorije")
    @ResponseWrapper(localName = "VrniKategorijeResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.VrniKategorijeResponse")
    public ArrayOfKategorija vrniKategorije();

    /**
     * 
     * @param k
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DodajKategorijo", action = "http://tempuri.org/IKategorijaService/DodajKategorijo")
    @WebResult(name = "DodajKategorijoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DodajKategorijo", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.DodajKategorijo")
    @ResponseWrapper(localName = "DodajKategorijoResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.DodajKategorijoResponse")
    public Boolean dodajKategorijo(
        @WebParam(name = "k", targetNamespace = "http://tempuri.org/")
        Kategorija k);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IzbrisiKategorijo", action = "http://tempuri.org/IKategorijaService/IzbrisiKategorijo")
    @WebResult(name = "IzbrisiKategorijoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IzbrisiKategorijo", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.IzbrisiKategorijo")
    @ResponseWrapper(localName = "IzbrisiKategorijoResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.IzbrisiKategorijoResponse")
    public Boolean izbrisiKategorijo(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        Integer id);

    /**
     * 
     * @param nk
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DodajNarocenoKategorijo", action = "http://tempuri.org/IKategorijaService/DodajNarocenoKategorijo")
    @WebResult(name = "DodajNarocenoKategorijoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DodajNarocenoKategorijo", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.DodajNarocenoKategorijo")
    @ResponseWrapper(localName = "DodajNarocenoKategorijoResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.DodajNarocenoKategorijoResponse")
    public Boolean dodajNarocenoKategorijo(
        @WebParam(name = "nk", targetNamespace = "http://tempuri.org/")
        NarocenaKategorija nk);

    /**
     * 
     * @param u
     * @param k
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IzbrisiNarocenoKategorijo", action = "http://tempuri.org/IKategorijaService/IzbrisiNarocenoKategorijo")
    @WebResult(name = "IzbrisiNarocenoKategorijoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IzbrisiNarocenoKategorijo", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.IzbrisiNarocenoKategorijo")
    @ResponseWrapper(localName = "IzbrisiNarocenoKategorijoResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.IzbrisiNarocenoKategorijoResponse")
    public Boolean izbrisiNarocenoKategorijo(
        @WebParam(name = "u", targetNamespace = "http://tempuri.org/")
        Uporabnik u,
        @WebParam(name = "k", targetNamespace = "http://tempuri.org/")
        Kategorija k);

    /**
     * 
     * @param u
     * @return
     *     returns com.fleamart.kategorija.ws.ArrayOfKategorija
     */
    @WebMethod(operationName = "VrniNaroceneKategorije", action = "http://tempuri.org/IKategorijaService/VrniNaroceneKategorije")
    @WebResult(name = "VrniNaroceneKategorijeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VrniNaroceneKategorije", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.VrniNaroceneKategorije")
    @ResponseWrapper(localName = "VrniNaroceneKategorijeResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.VrniNaroceneKategorijeResponse")
    public ArrayOfKategorija vrniNaroceneKategorije(
        @WebParam(name = "u", targetNamespace = "http://tempuri.org/")
        Uporabnik u);

    /**
     * 
     * @param k
     * @return
     *     returns com.fleamart.kategorija.ws.ArrayOfUporabnik
     */
    @WebMethod(operationName = "VrniNaroceneUporabnike", action = "http://tempuri.org/IKategorijaService/VrniNaroceneUporabnike")
    @WebResult(name = "VrniNaroceneUporabnikeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VrniNaroceneUporabnike", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.VrniNaroceneUporabnike")
    @ResponseWrapper(localName = "VrniNaroceneUporabnikeResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.kategorija.ws.VrniNaroceneUporabnikeResponse")
    public ArrayOfUporabnik vrniNaroceneUporabnike(
        @WebParam(name = "k", targetNamespace = "http://tempuri.org/")
        Kategorija k);

}
