
package com.fleamart.oglas.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OglasService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:1691/OglasService.svc?wsdl")
public class OglasService
    extends Service
{

    private final static URL OGLASSERVICE_WSDL_LOCATION;
    private final static WebServiceException OGLASSERVICE_EXCEPTION;
    private final static QName OGLASSERVICE_QNAME = new QName("http://tempuri.org/", "OglasService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1691/OglasService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OGLASSERVICE_WSDL_LOCATION = url;
        OGLASSERVICE_EXCEPTION = e;
    }

    public OglasService() {
        super(__getWsdlLocation(), OGLASSERVICE_QNAME);
    }

    public OglasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OGLASSERVICE_QNAME, features);
    }

    public OglasService(URL wsdlLocation) {
        super(wsdlLocation, OGLASSERVICE_QNAME);
    }

    public OglasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OGLASSERVICE_QNAME, features);
    }

    public OglasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OglasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IOglasService
     */
    @WebEndpoint(name = "BasicHttpBinding_IOglasService")
    public IOglasService getBasicHttpBindingIOglasService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IOglasService"), IOglasService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IOglasService
     */
    @WebEndpoint(name = "BasicHttpBinding_IOglasService")
    public IOglasService getBasicHttpBindingIOglasService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IOglasService"), IOglasService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OGLASSERVICE_EXCEPTION!= null) {
            throw OGLASSERVICE_EXCEPTION;
        }
        return OGLASSERVICE_WSDL_LOCATION;
    }

}
