
package com.fleamart.ponudba.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPonudbaService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPonudbaService {


    /**
     * 
     * @param p
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "http://tempuri.org/IPonudbaService/placeBidOnItem")
    @WebResult(name = "placeBidOnItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "placeBidOnItem", targetNamespace = "http://tempuri.org/", className = "com.fleamart.ponudba.ws.PlaceBidOnItem")
    @ResponseWrapper(localName = "placeBidOnItemResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.ponudba.ws.PlaceBidOnItemResponse")
    public Boolean placeBidOnItem(
        @WebParam(name = "p", targetNamespace = "http://tempuri.org/")
        Ponudba p);

}
