
package com.fleamart.ponudba.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PonudbaService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:1691/PonudbaService.svc?WSDL")
public class PonudbaService
    extends Service
{

    private final static URL PONUDBASERVICE_WSDL_LOCATION;
    private final static WebServiceException PONUDBASERVICE_EXCEPTION;
    private final static QName PONUDBASERVICE_QNAME = new QName("http://tempuri.org/", "PonudbaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1691/PonudbaService.svc?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PONUDBASERVICE_WSDL_LOCATION = url;
        PONUDBASERVICE_EXCEPTION = e;
    }

    public PonudbaService() {
        super(__getWsdlLocation(), PONUDBASERVICE_QNAME);
    }

    public PonudbaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PONUDBASERVICE_QNAME, features);
    }

    public PonudbaService(URL wsdlLocation) {
        super(wsdlLocation, PONUDBASERVICE_QNAME);
    }

    public PonudbaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PONUDBASERVICE_QNAME, features);
    }

    public PonudbaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PonudbaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IPonudbaService
     */
    @WebEndpoint(name = "BasicHttpBinding_IPonudbaService")
    public IPonudbaService getBasicHttpBindingIPonudbaService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IPonudbaService"), IPonudbaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPonudbaService
     */
    @WebEndpoint(name = "BasicHttpBinding_IPonudbaService")
    public IPonudbaService getBasicHttpBindingIPonudbaService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IPonudbaService"), IPonudbaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PONUDBASERVICE_EXCEPTION!= null) {
            throw PONUDBASERVICE_EXCEPTION;
        }
        return PONUDBASERVICE_WSDL_LOCATION;
    }

}
