
package com.fleamart.uporabnik.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUporabnikService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUporabnikService {


    /**
     * 
     * @param uporabnik
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IUporabnikService/registrirajUporabnika")
    @WebResult(name = "registrirajUporabnikaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "registrirajUporabnika", targetNamespace = "http://tempuri.org/", className = "com.fleamart.uporabnik.ws.RegistrirajUporabnika")
    @ResponseWrapper(localName = "registrirajUporabnikaResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.uporabnik.ws.RegistrirajUporabnikaResponse")
    public String registrirajUporabnika(
        @WebParam(name = "uporabnik", targetNamespace = "http://tempuri.org/")
        Uporabnik uporabnik);

    /**
     * 
     * @param upImeV
     * @param passV
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "http://tempuri.org/IUporabnikService/loginCheck")
    @WebResult(name = "loginCheckResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "loginCheck", targetNamespace = "http://tempuri.org/", className = "com.fleamart.uporabnik.ws.LoginCheck")
    @ResponseWrapper(localName = "loginCheckResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.uporabnik.ws.LoginCheckResponse")
    public Integer loginCheck(
        @WebParam(name = "upImeV", targetNamespace = "http://tempuri.org/")
        String upImeV,
        @WebParam(name = "passV", targetNamespace = "http://tempuri.org/")
        String passV);

    /**
     * 
     * @param id
     * @return
     *     returns com.fleamart.uporabnik.ws.Uporabnik
     */
    @WebMethod(operationName = "ReadUporabnik", action = "http://tempuri.org/IUporabnikService/ReadUporabnik")
    @WebResult(name = "ReadUporabnikResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReadUporabnik", targetNamespace = "http://tempuri.org/", className = "com.fleamart.uporabnik.ws.ReadUporabnik")
    @ResponseWrapper(localName = "ReadUporabnikResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.uporabnik.ws.ReadUporabnikResponse")
    public Uporabnik readUporabnik(
        @WebParam(name = "Id", targetNamespace = "http://tempuri.org/")
        Integer id);

    /**
     * 
     * @param id
     * @return
     *     returns com.fleamart.uporabnik.ws.Uporabnik
     */
    @WebMethod(operationName = "ProfilUporabnika", action = "http://tempuri.org/IUporabnikService/ProfilUporabnika")
    @WebResult(name = "ProfilUporabnikaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProfilUporabnika", targetNamespace = "http://tempuri.org/", className = "com.fleamart.uporabnik.ws.ProfilUporabnika")
    @ResponseWrapper(localName = "ProfilUporabnikaResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.uporabnik.ws.ProfilUporabnikaResponse")
    public Uporabnik profilUporabnika(
        @WebParam(name = "Id", targetNamespace = "http://tempuri.org/")
        Integer id);

}
