
package com.fleamart.uporabnik.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUporabnikService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUporabnikService {


    /**
     * 
     * @param uporabnik
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IUporabnikService/registrirajUporabnika")
    @WebResult(name = "registrirajUporabnikaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "registrirajUporabnika", targetNamespace = "http://tempuri.org/", className = "com.fleamart.uporabnik.ws.RegistrirajUporabnika")
    @ResponseWrapper(localName = "registrirajUporabnikaResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.uporabnik.ws.RegistrirajUporabnikaResponse")
    public String registrirajUporabnika(
        @WebParam(name = "uporabnik", targetNamespace = "http://tempuri.org/")
        Uporabnik uporabnik);

}
