
package com.fleamart.oceni.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IOcenaService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IOcenaService {


    /**
     * 
     * @param kupecId
     * @return
     *     returns com.fleamart.oceni.ws.ArrayOfOglas
     */
    @WebMethod(operationName = "VrniNeocenjeneOglaseKupca", action = "http://tempuri.org/IOcenaService/VrniNeocenjeneOglaseKupca")
    @WebResult(name = "VrniNeocenjeneOglaseKupcaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VrniNeocenjeneOglaseKupca", targetNamespace = "http://tempuri.org/", className = "com.fleamart.oceni.ws.VrniNeocenjeneOglaseKupca")
    @ResponseWrapper(localName = "VrniNeocenjeneOglaseKupcaResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.oceni.ws.VrniNeocenjeneOglaseKupcaResponse")
    public ArrayOfOglas vrniNeocenjeneOglaseKupca(
        @WebParam(name = "kupecId", targetNamespace = "http://tempuri.org/")
        Integer kupecId);

    /**
     * 
     * @param ocena
     * @param kupecId
     */
    @WebMethod(action = "http://tempuri.org/IOcenaService/oceniOglas")
    @RequestWrapper(localName = "oceniOglas", targetNamespace = "http://tempuri.org/", className = "com.fleamart.oceni.ws.OceniOglas")
    @ResponseWrapper(localName = "oceniOglasResponse", targetNamespace = "http://tempuri.org/", className = "com.fleamart.oceni.ws.OceniOglasResponse")
    public void oceniOglas(
        @WebParam(name = "kupecId", targetNamespace = "http://tempuri.org/")
        Integer kupecId,
        @WebParam(name = "ocena", targetNamespace = "http://tempuri.org/")
        ArrayOfOcenaDTO ocena);

}
